feat(sprint-details.component.html): fixed UI
Worktrolly/worktrolly pull request #100
Opened 2021-01-21 19:03 UTC by AvinashMahanthi

### Functionality:
fix completed sprint button UI

### Solution:
added some changes and reversed the filter sprint button and complete sprint button.

### Risk level:
- [  ] high 
- [ ] medium
- [ ] low

### How to test:
ng serve
go to the dashboard
![image](https://user-images.githubusercontent.com/54079190/105399139-3cf52980-5c49-11eb-96c7-037939388715.png)

![image](https://user-images.githubusercontent.com/54079190/105399193-51392680-5c49-11eb-91d6-b34c2511114e.png)

![image](https://user-images.githubusercontent.com/54079190/105399306-72017c00-5c49-11eb-9ab3-0a059ebe1fa9.png)

2021-01-23 04:20 UTC, shivamgoyal7 requested changes
Still need to work in UI.
The gap between button should not be there.
And also fix this in mobile view

2021-01-26 05:14 UTC, shivamgoyal7 requested changes
complete this asap

2021-01-26 05:14 UTC, shivamgoyal7 commented on worktrolly-ui/src/app/body/board/board.component.ts
>      this.currentSprintName = "S" + this.currentSprintNumber;
this is not exactly correct, check again

2021-01-26 13:57 UTC, shivamgoyal7 requested changes
still need to work on UI

2021-01-26 13:57 UTC, shivamgoyal7 commented on worktrolly-ui/src/app/body/board/sprint-details/sprint-details.component.html
> +                <div class="col-md-3 col-1">
col-md-7, col-6

2021-01-26 13:57 UTC, shivamgoyal7 commented on worktrolly-ui/src/app/body/board/sprint-details/sprint-details.component.html
> +                                <div class="col-6 pl-2">
line 11:  col-md-7 col-6

and first put the filter then completed

and completed button changed to be a status button where two option should be there under progress and completed, if status is under progress it simply update in database else same now u did.

and also align the icon using vertical alignment style

remove ml auto from line 12

and increase the size of input box in filter

2021-01-29 11:36 UTC, AvinashMahanthi commented
pc view:
![image](https://user-images.githubusercontent.com/54079190/106270532-2572fd80-6254-11eb-9928-2885cc12f4f8.png)

mobile view:
![Screenshot (210)](https://user-images.githubusercontent.com/54079190/106270679-594e2300-6254-11eb-93ab-678799da3dec.png)

2021-01-29 11:45 UTC, shivamgoyal7 approved these changes
Ship it

2021-01-30 12:39 UTC, viv9k requested changes
Please complete the required changes asap.

2021-01-30 12:39 UTC, viv9k commented on worktrolly-ui/src/app/body/board/sprint-details/sprint-details.component.ts
> +    console.error("Error", error);
Reduce the code by reusing the methods with different arguments. So underProgress and completed can use the same method.

2021-01-30 12:39 UTC, viv9k commented on worktrolly-ui/src/app/body/board/sprint-details/sprint-details.component.html
> +                            <div class="dropdown-item" type="button" (click)="completeSprint()">Completed</div>
Use the same methods with different arguments.

2021-02-03 15:18 UTC, Shrishti1802 commented
Resolve merge conflicts

2021-02-06 06:24 UTC, viv9k commented
no action taken on this since last 3 days

2021-02-06 08:59 UTC, closed without merging