feat(Chart): Added Performance Chart Component
Worktrolly/worktrolly pull request #102
Opened 2021-01-23 18:02 UTC by sandeep-v1404

Signed-off-by: sandeep-v1404 <valpasanisandeep@gmail.com>

### Functionality:

To show Performance Chart in Dashboard . And also to query with custom sprint range.

### Solution:

To implement chart using Google Charts. And also to make low level components.

### Risk level:
- [X] high 
- [ ] medium
- [ ] low

### How to test:

- ng serve
- In main Page, left side there is performance chart .
- Query using the top right icon to know your performance in previous sprints.

### 

Reference:

1.Desktop/PC/Laptop view
![ChartWork](https://user-images.githubusercontent.com/57038543/105609992-d7cd3f80-5dd2-11eb-88b1-9931483843e2.png)

2.Mobile View
![ChartWorkMobile](https://user-images.githubusercontent.com/57038543/105610019-0e0abf00-5dd3-11eb-8fca-4cf9bffc6828.png)

2021-01-26 05:39 UTC, Shrishti1802 commented
Resolve merge conflicts

2021-01-26 09:26 UTC, shivamgoyal7 requested changes
In validation some extra changes occur so please undo that changes

2021-01-26 09:40 UTC, sandeep-v1404 commented on worktrolly-ui/package-lock.json
> +  "version": "0.2.0",
> In validation some extra changes occur so please undo that changes

Formatting was done properly by @k0malSharma's branch -> validation service file . Now it was fixed Correctly.

2021-01-26 09:42 UTC, shivamgoyal7 commented on worktrolly-ui/package-lock.json
> +  "version": "0.2.0",
ok

2021-01-26 09:53 UTC, shivamgoyal7 approved these changes
ship it

2021-01-26 10:30 UTC, viv9k approved these changes
Ship it

2021-01-26 10:30 UTC, viv9k commented on worktrolly-ui/package.json
> +        "zone.js": "~0.10.2"
Revert these changes

2021-01-26 10:31 UTC, viv9k requested changes
Please complete the required changes

2021-01-26 10:59 UTC, sandeep-v1404 commented
> Please complete the required changes

Yes , It was done automatically according to alphabetical order.

2021-01-27 11:19 UTC, viv9k approved these changes
Ship it

2021-01-28 12:53 UTC, merged