Added completion date and made patch for Completion Date in older tasks
Worktrolly/worktrolly pull request #105
Opened 2021-01-27 17:24 UTC by arjund-06

Signed-off-by: Arjun Dave <davearjun25@gmail.com>

### Functionality:
Shows completion date when the user submits Status as "Completed" while logging a task and older tasks which are completed have completion date as "XX/XX/XXXX".

### Solution:
Changed the firebase functions,
Added lines to create a CompletionDate field with value "Not yet Completed" while creating a new task and in log work added lines to update the same field to the current date on logging task as Completed.

### Risk level:
- [ ] high 
- [X] medium
- [ ] low

### How to test:
1. First, deploy the functions file in the code.
2. Use the patch to mark older Completed tasks with the date "XX/XX/XXXX"
3. ng serve
4. Create a new task and then log work and mark task as completed and voila Completion Date appears in the Task Detail page.

### Pictures of the updated Task Detail page:

#### When the task isn't completed,

![image](https://user-images.githubusercontent.com/58979519/106028568-1d9b4800-60f2-11eb-96fd-746f9a9e4ccc.png)

#### After Completing the task,

![image](https://user-images.githubusercontent.com/58979519/106028774-60f5b680-60f2-11eb-9457-6625f5b619fa.png)

2021-01-28 15:42 UTC, shivamgoyal7 requested changes
1. can u check that u have used the correct formatter in index.js.
2. completion date position in task-detail is not correct. It should be at the top right corner and decrease the font size.
3. make a new file in app folder with patch name and click button there

2021-01-29 16:48 UTC, arjund-06 commented
One tiny error, will reopen

2021-01-30 16:59 UTC, shivamgoyal7 approved these changes
ship it

2021-02-02 11:55 UTC, Shrishti1802 commented
Please resolve merge conflicts

2021-02-06 06:38 UTC, viv9k requested changes
Complete the required changes asap

2021-02-06 06:38 UTC, viv9k commented on functions/patchAPI.js
> +        var p1 = db.collection("Tasks").get().then((querySnapshot) => {
convert these into let and const type, according to the requirement, Do also use eslint for tracking these issue.

2021-02-06 06:38 UTC, viv9k commented on functions/patchAPI.js
> +        var p1 = db.collection("Tasks").get().then((querySnapshot) => {
Name querySnapshot is not good, please use something understandable.

2021-02-06 06:38 UTC, viv9k commented on functions/patchAPI.js
> +                db.collection("Tasks").doc(id).update({
Use eslint to track the bug here

2021-02-06 06:38 UTC, viv9k commented on src/app/body/task-details/task-details.component.html
> +                                <span type="button" class="material-icons text-light mr-3" data-bs-toggle="tooltip" data-bs-placement="top" title="Delete" *ngIf="authService.afauth.user | async" (cli
What is the need of doing change here.

2021-02-06 06:38 UTC, viv9k commented on src/app/body/task-details/task-details.component.html
> +                            <div id="creationDateTaskDescription">{{task.CompletionDate}}</div>
Make the UI little better

2021-02-06 07:49 UTC, arjund-06 commented on src/app/body/task-details/task-details.component.html
> +                                <span type="button" class="material-icons text-light mr-3" data-bs-toggle="tooltip" data-bs-placement="top" title="Delete" *ngIf="authService.afauth.user | async" (cli
@bighnesh0404 told me to do this...

2021-02-08 04:51 UTC, viv9k requested changes
Please fix the required changes

2021-02-08 04:51 UTC, viv9k commented on src/app/app.module.ts
> +    FilterTaskComponent,
Multiple addition of filter task components seen, please fix

2021-02-08 12:39 UTC, bighnesh0404 approved these changes
Ship it

2021-02-08 13:13 UTC, viv9k approved these changes
ship it

2021-02-09 15:36 UTC, merged