Dev/error
Worktrolly/worktrolly pull request #118
Opened 2021-02-04 19:56 UTC by AvinashMahanthi

### Functionality:
Throw error whenever there is an internal or external error.

### Solution:
Add Error Component, Error Handler Service and error xml

### Risk level:
- [X] high 
- [ ] medium
- [ ] low

### How to test:

- ng serve
- firebase emulators: start
- Press Submit button without filling input fields.
- Then you can see the Error.

### ScreenShot:
![image](https://user-images.githubusercontent.com/54079190/106947912-0e02ab80-6751-11eb-8c1e-04b4750cd5f8.png)

2021-02-06 06:23 UTC, viv9k commented
If there is no sub component then 0000 should be shown. There should be 12 digits of error code.

2021-02-06 06:23 UTC, viv9k commented
If there is no sub component then 0000 should be shown. There should be 12 digits of error code.

2021-02-08 17:32 UTC, bighnesh0404 requested changes

2021-02-08 17:32 UTC, bighnesh0404 commented on src/app/app.module.ts
> +    HttpClientModule,
remove the comma from here

2021-02-10 11:03 UTC, viv9k commented
Please resolve merge conflict asap

2021-02-12 04:57 UTC, viv9k commented
Please review this code asap
tomorrow we need to give release

2021-02-12 08:49 UTC, viv9k approved these changes
ship it

2021-02-12 16:53 UTC, bighnesh0404 approved these changes

2021-02-13 08:26 UTC, merged