feat(Navbar): Fixed Navbar Functionality
Worktrolly/worktrolly pull request #119
Opened 2021-02-06 09:13 UTC by sandeep-v1404

Signed-off-by: sandeep-v1404 <valpasanisandeep@gmail.com>

### Functionality:
Fix Bugs in Navbar

### Solution:
Modified Functions and Added New Function to make Navbar Functionality bug free.

### Risk level:
- [ ] high 
- [X] medium
- [ ] low

### How to test:

- ng serve
- firebase emulators:start
- Check Navbar Below Header.

### Screenshot:
![image](https://user-images.githubusercontent.com/57038543/107114125-88cee200-6889-11eb-977d-51f9d70d57c4.png)

2021-02-08 17:07 UTC, bighnesh0404 approved these changes

2021-02-08 17:07 UTC, bighnesh0404 approved these changes
Ship it

2021-02-10 11:12 UTC, viv9k requested changes
Please complete the required changes and get them completed.

2021-02-10 11:12 UTC, viv9k commented on src/app/app-routing.module.ts
> +  { path: 'Tasks/:category/:currentSprintName/:taskId', component: TaskDetailsComponent },
We don't need currentSprintName here

2021-02-10 11:12 UTC, viv9k commented on src/app/body/tasks/task-cards/task-cards.component.ts
> +    this.router.navigate(['/Tasks', this.task.Category, this.sprintName, id]);
We don't need sprint name in route

2021-02-10 11:12 UTC, viv9k commented on src/app/body/tasks/tasks.component.html
> +                        <app-task-cards [task]="item" [sprintName]="currentSprintName"></app-task-cards>
We don't need to send current sprint name

2021-02-10 11:12 UTC, viv9k commented on src/app/body/tasks/tasks.component.ts
> +    this.navbarHandlerService.setNavbar("Board");
We don't need to set Board as Navbar here

2021-02-10 11:12 UTC, viv9k commented on src/app/services/navbar-handler.service.ts
> +    this.navbarString = ""
Please use old logic of navbar so that we can make use of it later

2021-02-12 04:55 UTC, viv9k requested changes
Fix the required changes asap.

2021-02-12 04:55 UTC, viv9k commented on src/environments/environment.ts
> +
revert this file

2021-02-12 06:00 UTC, sandeep-v1404 commented on src/environments/environment.ts
> +
Done Bhaiya

2021-02-12 06:02 UTC, viv9k approved these changes
ship it

2021-02-13 08:27 UTC, k0malSharma commented
Please resolve merge conflicts as soon as possible

2021-02-13 10:07 UTC, merged