feat(Sprint-details): resolved Current sprint button.
Worktrolly/worktrolly pull request #120
Opened 2021-02-06 10:13 UTC by AvinashMahanthi

Signed-off-by: AvinashMahanthi <avinashfab5678@gmail.com>

### Functionality:
Show Current sprint button when Sprint is in Under progress

### Solution:
Added dropdown for Sprint status, hiding the button when Status is Completed.

### Risk level:
- [ ] high 
- [X] medium
- [ ] low

### How to test:

- ng serve
- firebase emulators:start
- Go to board, check the sprint details.

### Screenshot:
![image](https://user-images.githubusercontent.com/54079190/107115325-e0714b80-6891-11eb-895f-d475886b53f7.png)

2021-02-07 12:18 UTC, shivamgoyal7 requested changes
Add screenshot of UI

2021-02-07 12:18 UTC, shivamgoyal7 commented on src/app/body/board/board.component.html
> +                        </app-feature-card>
undo this change

2021-02-07 12:18 UTC, shivamgoyal7 commented on src/app/body/board/board.component.html
> +                </app-sprint-details>
undo this change

2021-02-07 13:16 UTC, AvinashMahanthi commented on src/app/body/board/board.component.html
> +                </app-sprint-details>
Done

2021-02-08 13:12 UTC, shivamgoyal7 requested changes

2021-02-08 13:12 UTC, shivamgoyal7 commented on src/app/body/board/sprint-details/sprint-details.component.ts
> +      const result = await callable({ CurrentSprintName: this.currentSprintName, SprintStatus: updateStatus }).toPromise();
Here in line 41 this.sprintstaus will come instead of updatestatus

2021-02-08 13:15 UTC, shivamgoyal7 commented on src/app/body/board/sprint-details/sprint-details.component.ts
> +      const result = await callable({ CurrentSprintName: this.currentSprintName, SprintStatus: updateStatus }).toPromise();
If u are using update status then remove line36

2021-02-09 07:26 UTC, shivamgoyal7 approved these changes
ship it

2021-02-12 05:01 UTC, viv9k requested changes
Fix the required changes

2021-02-16 04:19 UTC, shivamgoyal7 commented
resolve conflict

2021-02-18 06:48 UTC, closed without merging

2021-02-18 15:38 UTC, viv9k commented
Why is this PR closed, Please reopen it

2021-02-18 17:52 UTC, AvinashMahanthi commented
Due to the latest changes some files have been corrupted in this branch, I had done this on the other branch ie. PR No: #130