Dev/header
Worktrolly/worktrolly pull request #121
Opened 2021-02-09 09:27 UTC by arjund-06

### Functionality:
Makes Navbar more funtional.

### Solution:
Grouped the create task and start sprint buttons and grouped the board buttons and added button to create team and add members.

### Risk level:
- [ ] high 
- [ ] medium
- [X] low

### How to test:
1. Use ng serve and see the difference in the Navbar.

2021-02-10 17:27 UTC, shivamgoyal7 requested changes
make a separate pr for header and patch

2021-02-10 17:31 UTC, shivamgoyal7 requested changes
do these changes asap

2021-02-10 17:31 UTC, shivamgoyal7 commented on src/app/app.module.ts
> +    FilterTaskComponent,
remove FilterTaskcomponent it is added three times.Check it

2021-02-10 17:31 UTC, shivamgoyal7 commented on src/app/app.module.ts
> +import { RangeCardComponent } from "./body/my-dashboard/performance-chart/range-card/range-card.component";
add semicolon

2021-02-10 17:31 UTC, shivamgoyal7 commented on src/app/body/task-details/task-details.component.html
> +                        </div>
revert the changes from this file

2021-02-11 14:39 UTC, closed without merging

2021-02-11 14:40 UTC, arjund-06 commented
Closed because it had commits from two different tasks