Dev/header
Worktrolly/worktrolly pull request #122
Opened 2021-02-12 05:27 UTC by arjund-06

### Functionality:
Makes Navbar more funtional.

### Solution:
Grouped the create task and start sprint buttons and grouped the board buttons and added button to create team and add members.

### Risk level:
- [ ] high 
- [ ] medium
- [X] low

### How to test:
1. Use ng serve and see the difference in the Navbar.

Picture of navbar:

![image](https://user-images.githubusercontent.com/58979519/107733397-f7e08680-6d20-11eb-9113-2bc74bdcdc90.png)

2021-02-13 13:14 UTC, bighnesh0404 approved these changes
working properly without any error, ship it

2021-02-16 17:13 UTC, viv9k requested changes
Please complete the required changes

2021-02-16 17:13 UTC, viv9k commented on src/app/body/board/focus-nav/focus-nav.component.css
> +} */
Please remove the commented code

2021-02-17 14:16 UTC, viv9k approved these changes
Ship it!!

2021-02-17 15:04 UTC, merged