feat(sprint-details): Deleted details and Updated Status btn.
Worktrolly/worktrolly pull request #130
Opened 2021-02-18 10:15 UTC by AvinashMahanthi

Signed-off-by: AvinashMahanthi <avinashfab5678@gmail.com>

### Functionality:
Remove the Sprint Details and update the Sprint Status button.

### Solution:

- Updated the Sprint status to the dropdown button.
- Removed the Sprint Details row.

### Risk level:
- [ ] high 
- [ ] medium
- [x] low

### How to test:

- ng serve
- firebase emulators:start
- Go to Board.

2021-02-18 12:14 UTC, shivamgoyal7 approved these changes
Ship it

2021-02-19 12:38 UTC, viv9k requested changes
Please complete the required changes asap.

2021-02-19 12:38 UTC, viv9k commented on src/app/body/board/sprint-details/sprint-details.component.html
> +        <div class="card-body" style="background-color:#202124;">
Please move all style tag in .css

2021-02-19 12:38 UTC, viv9k commented on src/app/body/board/sprint-details/sprint-details.component.html
> +                <div class="row col-md-3 col-8 text-right">
column and row merged in same line is not a right approach.
Please fix it

2021-02-19 12:38 UTC, viv9k commented on src/app/body/board/sprint-details/sprint-details.component.html
> +                    <div class="mr-1">
just for margin a div tag with class, we can give padding once column is implemented.

2021-02-19 12:38 UTC, viv9k commented on src/app/body/board/sprint-details/sprint-details.component.html
> +                                        <button class="btn" id="dropdownButton" style="font-size: 14px;" (click)="changeSprintNumber()">Filter</button>
Please move style tag in .css

2021-02-19 12:38 UTC, viv9k commented on src/app/body/board/sprint-details/sprint-details.component.html
> +        <div class="card-header" style="font-weight: bold; background-color: #5A20F0; color:white;">
Please move style tag into .css

2021-02-19 12:38 UTC, viv9k commented on src/app/body/board/sprint-details/sprint-details.component.html
> +        </div>
Move all the style tags in .css using common class.

2021-02-19 12:38 UTC, viv9k commented on src/app/body/board/sprint-details/sprint-details.component.ts
> +  enableLoader: boolean = false;
Loader is being implemented but not available in html, call the loading spinner in css until the api call is completed.

2021-02-22 08:39 UTC, viv9k commented
resolve merge conflict and adapt your code with new theme based implementation.

2021-03-02 19:09 UTC, closed without merging