Dev/verification mail
Worktrolly/worktrolly pull request #144
Opened 2021-03-10 16:44 UTC by shivamgoyal7

### Functionality:
user varification through mail

### Solution:
Mail is sent to all the members to verify user authenticate.

### Risk level:
- [ ] high 
- [ ] medium
- [ ] low

### How to test:
deploy firebase

2021-03-14 11:49 UTC, viv9k commented
I want demo on this today evening

2021-03-14 11:53 UTC, viv9k commented
also change the target branch to Adding-organization-feature

2021-03-16 15:55 UTC, viv9k requested changes
Please complete the required changes

2021-03-17 06:05 UTC, shivamgoyal7 commented on functions/createNewOrgAPI.js
> +const sendEmail = require("./sendEmailAPI.js");
done

2021-03-17 06:05 UTC, shivamgoyal7 commented on functions/createNewOrgAPI.js
> +            sendEmail.sendVerificationEmail(teamName, teamManagerEmail, teamDescription, element, organizationDomain);
done

2021-03-17 06:05 UTC, shivamgoyal7 commented on functions/sendEmailAPI.js
> +};
done

2021-03-17 06:06 UTC, shivamgoyal7 commented on src/app/app-routing.module.ts
> +  { path: 'verifyUser/:organizationDomain/:teamName/:userEmail', component: UserVerificationComponent, canActivate: [AngularFireAuthGuard] },
yes it is working but it redirects to dashboard so I have removed it and use condition to handle

2021-03-17 08:02 UTC, viv9k requested changes
Please complete the required changes

2021-03-17 08:02 UTC, viv9k commented on src/app/app-routing.module.ts
> +  { path: 'verifyUser/:organizationDomain/:teamName/:userEmail', component: UserVerificationComponent, canActivate: [AngularFireAuthGuard] },
You can use something like: const redirectLoggedInToDashboard = () => redirectLoggedInTo(['']);

const redirectLoggedInToVerifyUser = () => redirectLoggedInTo(['verifyUser/orgDomain/teamName/userEmail']);

then add => data: { authGuardPipe: redirectLoggedInToVerifyUser }

2021-03-17 09:19 UTC, shivamgoyal7 commented
changes are not coming in this pr

2021-03-17 09:19 UTC, shivamgoyal7 commented
so im closing this pr

2021-03-17 09:19 UTC, closed without merging