Dev/trash
Worktrolly/worktrolly pull request #145
Opened 2021-03-12 08:05 UTC by arjund-06

### Functionality:
Show the tasks that have been deleted.

### Solution:
Made the deleted tasks work like BackLog and any other sprint with the Main details like TotalTasks etc..

### Risk level:
- [x] high 
- [ ] medium
- [ ] low

### How to test:
1. firebase emulators:start
2. ng serve
3. Create a new sprint and new task.
4. Now delete that task
5. In board component click the Deleted tab in focus nav and view deleted tasks

### Pics:

![image](https://user-images.githubusercontent.com/58979519/110910700-b6e78c00-8337-11eb-8242-9fcb1a2f6871.png)

![image](https://user-images.githubusercontent.com/58979519/110910728-bf3fc700-8337-11eb-8611-03824f6e2bc3.png)

2021-03-13 18:53 UTC, shivamgoyal7 requested changes
you can disable sprint details if possible..
or
instead of disabling put "---" in the place of xx/xx/xx and not started

2021-03-13 18:53 UTC, shivamgoyal7 commented on functions/deleteTaskAPI.js
> +                    Status: "Not Started",
these things are not required here.
You can disable sprint details

2021-03-13 18:53 UTC, shivamgoyal7 commented on functions/deleteTaskAPI.js
> +
remove this extra line no. 123

2021-03-15 15:19 UTC, shivamgoyal7 commented
resolve conflict

2021-03-16 08:40 UTC, shivamgoyal7 requested changes

2021-03-16 08:40 UTC, shivamgoyal7 commented on functions/deleteTaskAPI.js
> +                totalUnCompletedTask = doc.data().TotalUnCompletedTask;
we dont need these counter totalCompletedTask, totalUnCompletedTask
and also change others name to totalDevelopmentTaskDeleted....

2021-03-16 08:40 UTC, shivamgoyal7 commented on functions/deleteTaskAPI.js
> +                    TotalUnCompletedTask: totalUnCompletedTask,
delete this

2021-05-03 08:29 UTC, arjund-06 commented
I am closing this Pull request cuz I made all necessary changes in #164 with the updated API.

2021-05-03 08:29 UTC, closed without merging