Feat(): Completed Create Team feature
Worktrolly/worktrolly pull request #168
Opened 2021-05-06 15:01 UTC by sid-bagwe

Signed-off-by: sid-bagwe <siddhesh.ab@somaiya.edu>

### Functionality:
Called the 'Create Team' page on 'Create Team' button click with the required information fetched.

### Solution:
Created a new service i.e. org-team-service for fetching the team details and used router to call the 'Create Team' page.

### Risk level:
- [ ] high 
- [ ] medium
- [ ] low

### How to test:
ng serve
firebase emulators: start

2021-05-06 16:48 UTC, shivamgoyal7 requested changes
solve a bug in API. Now while updating team data, the organization domain is not receiving in API
and while updating we need to update() not set() in firestore.

Read data in service according to ApiKey

2021-05-06 16:48 UTC, shivamgoyal7 commented on src/app/header/header.component.html
> +                    <a class="dropdown-item " (click) = "callTeamPage()">Create Team</a>
change method name to createTeam()

2021-05-06 16:48 UTC, shivamgoyal7 commented on src/app/header/header.component.ts
> +  callTeamPage(){
change method name

2021-05-06 16:48 UTC, shivamgoyal7 commented on src/app/services/org-team.service.ts
> +    this.teamDocument = this.db.doc<Team>(documentPath);
Read data on the basis of appkey. Now it works for only one organization, when we have multipe organization then we need to select organization on the bais of appkey

2021-05-06 16:48 UTC, shivamgoyal7 commented on src/app/services/org-team.service.ts
> +        return { ...data }
remove empty line

2021-05-06 18:26 UTC, sid-bagwe commented
Okay. Will make the necessary changes

2021-05-13 13:24 UTC, shivamgoyal7 commented on functions/createNewOrgAPI.js
> +                    });
Add team name  in update

2021-05-13 13:25 UTC, shivamgoyal7 approved these changes
Ship it

2021-05-14 17:34 UTC, viv9k requested changes
please connect with me on this

2021-05-14 17:34 UTC, viv9k commented on functions/createNewOrgAPI.js
> +                });
The logic here is not correct, you need to get the orgDomain above and then get the team, if team exists, then update else set.

2021-05-14 17:34 UTC, viv9k commented on src/app/body/create-new-organization/team-details/team-details.component.ts
> +    }
This is not needed every-time, only when we want to update the team details we need it, else we should keep the fields empty for to create the new team.

2021-05-14 17:34 UTC, viv9k commented on src/app/body/create-new-organization/team-details/team-details.component.ts
> +      appKey = "";
I think we don't need try catch here. Since we are not subscribing to anything.

2021-05-14 17:34 UTC, viv9k commented on src/app/services/org-team.service.ts
> +import { Injectable } from '@angular/core';
We don't need this service, since the job of this service is already being done in applicationSettingService.

2021-05-14 17:34 UTC, viv9k commented on src/app/services/org-team.service.ts
> +    this.router.navigate(['/CreateTeam']);
We don't need this static id's since they are only applicable to worktrolly, this information needs to be fetched from the backend.

2021-05-16 09:59 UTC, viv9k requested changes
Please fix the required changes and test all the possible scenario, before sending any code to us.

2021-05-16 09:59 UTC, viv9k commented on src/app/body/create-new-organization/team-details/team-details.component.ts
> +    }
I believe, even if selectedTeamId is not available we still need organizationDomain to create new team.

The code is sent without testing.

2021-05-16 09:59 UTC, viv9k commented on src/app/header/header.component.ts
> +    this.router.navigate(['/CreateTeam', this.authService.getTeamId()]);
To create a new team we don't need to send team id. It's only needed for updating the teams details. 

The code is sent without testing the full functionality.

2021-05-16 11:19 UTC, viv9k approved these changes
Ship it

2021-05-16 12:36 UTC, viv9k approved these changes
ship it

2021-05-16 12:36 UTC, merged