feat():implementation of  workcompletion graph completed
Worktrolly/worktrolly pull request #172
Opened 2021-05-16 06:20 UTC by Kanishk6677

Signed-off-by: Kanishk6677 <kanishkraj6677@gmail.com>

### Functionality:
Implemented Work Completion Graph for a given particular task

### Solution:
Used ng circle session charts to demonstrate the work done by passing the data of workdone

### Risk level:
- [ ] high 
- [ ] medium
- [ ] low

### How to test:
ng serve
firebase emulators: start

2021-05-16 09:28 UTC, viv9k commented
Is there any chart in Google chart?

If so better to use Google chart.

2021-05-16 09:28 UTC, viv9k commented
Is there any chart in Google chart?

If so better to use Google chart.

2021-05-16 12:57 UTC, Kanishk6677 commented
I was facing some problems in Google charts. Their pie's data is fetched
with little bit complexities


On Sun, 16 May 2021 at 14:58, Vivek Kumar ***@***.***> wrote:

> Is there any chart in Google chart?
>
> If so better to use Google chart.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Worktrolly/worktrolly/pull/172#issuecomment-841791725>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQTF5MX3U5CHXKJM4P6TT4DTN6F3NANCNFSM446UKI3A>
> .
>

2021-05-22 17:32 UTC, viv9k requested changes
Let's connect once to review this

2021-05-22 17:32 UTC, viv9k commented on src/app/app.module.ts
> +      titleColor:"#228B22"
Please try moving these information to component

2021-05-28 17:40 UTC, viv9k commented
Can we take quick action on this.

2021-05-29 05:11 UTC, Kanishk6677 commented
Sure, will do that. This week I had stuck with some issues. I will complete
it as soon as possible.

On Fri, May 28, 2021, 11:11 PM Vivek Kumar ***@***.***> wrote:

> Can we take quick action on this.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/Worktrolly/worktrolly/pull/172#issuecomment-850571131>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQTF5MQT4FBA24KOYOS6QCDTP7ITDANCNFSM446UKI3A>
> .
>

2021-06-10 12:06 UTC, viv9k approved these changes
Ship it

2021-06-10 18:18 UTC, merged