Dev/profile
Worktrolly/worktrolly pull request #176
Opened 2021-05-20 11:37 UTC by shivamgoyal7

### Functionality:
added profile page

### Solution:
added profile page and edit option to update user data

### Risk level:
- [ ] high 
- [ ] medium
- [ ] low

### How to test:
ng serve
firebase emulators

![1](https://user-images.githubusercontent.com/60148611/118972134-d8936e00-b98d-11eb-99e3-d0b6570b347f.png)
![2](https://user-images.githubusercontent.com/60148611/118972136-d9c49b00-b98d-11eb-9fb6-226c4dec79ae.png)

2021-05-22 17:41 UTC, viv9k requested changes
Please complete the required changes and show me before submitting it.

2021-05-22 17:41 UTC, viv9k commented on functions/createNewUserAPI.js
> +                    Bio: "",
"About Me : " would sound better than bio

2021-05-22 17:41 UTC, viv9k commented on functions/updateUserProfileAPI.js
> +            console.error("Error", error);
Can we merge this into addUsers api

2021-05-22 17:41 UTC, viv9k commented on src/app/Interface/UserInterface.ts
> +    Bio: string;
Bio --> About Me

2021-05-22 17:41 UTC, viv9k commented on src/app/body/profile/edit-profile/edit-profile.component.html
> +                        (click)="editProfile()">Save</button>
Better to use material icon

2021-05-22 17:41 UTC, viv9k commented on src/app/services/auth.service.ts
> +  }
Better to use About me

2021-05-28 17:41 UTC, viv9k commented
Let's take quick action on this for tomorrows release.

2021-06-02 06:02 UTC, shivamgoyal7 commented on functions/createNewUserAPI.js
> +                    Bio: "",
ok

2021-06-02 06:02 UTC, shivamgoyal7 commented on functions/updateUserProfileAPI.js
> +            console.error("Error", error);
ok

2021-06-03 14:36 UTC, viv9k approved these changes
Ship it

2021-06-03 14:44 UTC, viv9k approved these changes
Ship it

2021-06-05 14:38 UTC, merged