feat(Active-Sprint Bug fix):Used currentSprintNumber as a Input data-…
Worktrolly/worktrolly pull request #188
Opened 2021-06-16 06:52 UTC by Kanishk6677

Signed-off-by: Kanishk6677 <kanishkraj6677@gmail.com>

### Functionality:
Fixed the bug regarding Active Sprint button

### Solution:
Used Data binding via teamCurrentSprintNumber in other component

### Risk level:
- [ ] high 
- [ ] medium
- [ ] low

### How to test:
ng serve
firebase emulators:start

2021-06-16 15:52 UTC, shivamgoyal7 requested changes

2021-06-16 15:52 UTC, shivamgoyal7 commented on src/app/body/board/sprint-details/sprint-details.component.ts
> +import { Sprint,SprintDataId,TeamDataId } from 'src/app/Interface/TeamInterface';
revert this change, this is not required

2021-06-16 16:13 UTC, shivamgoyal7 requested changes
test the code properly, this code is not working properly

2021-06-16 16:13 UTC, shivamgoyal7 commented on src/app/body/board/board.component.html
> +                    <app-sprint-details [currentSprintName]="currentSprintName" [currentSprintNumber]="teamCurrentSprintNumber"  [sprintData]="sprintData" (currentSprint)="changeSprintNumber($event)"
check properly, this is not woking

2021-06-17 16:07 UTC, shivamgoyal7 approved these changes
ship it

2021-06-19 12:20 UTC, viv9k approved these changes
Ship it

2021-06-19 15:38 UTC, k0malSharma commented
Resolve merge conflict asap

2021-06-19 16:37 UTC, merged