Dev angular
Worktrolly/worktrolly pull request #189
Opened 2021-06-17 13:01 UTC by anu-aj

### Functionality:
Add folders in the services directory to separate each service

### Solution:
Folders created and organized

### Risk level:
- [ ] high 
- [ ] medium
- [x] low

### How to test:
1. ng serve
2. firebase emulators:start

2021-06-19 13:39 UTC, shivamgoyal7 requested changes
solve the conflict

2021-06-19 13:39 UTC, shivamgoyal7 commented on src/app/services/auth.service.ts
>    providedIn: 'root',
solve the conflict

2021-06-22 12:47 UTC, viv9k requested changes
Please fix the spelling of backend folder in services.

2021-06-24 14:57 UTC, viv9k approved these changes
Ship it

2021-06-26 15:46 UTC, merged