Dev patch3
Worktrolly/worktrolly pull request #204
Opened 2021-07-02 16:27 UTC by RohitVarma001

### Functionality:
Patch 3

### Solution:
Get the field name and field value from the user to get task details based on it and update the fields with new values in database

### Risk level:
- [ ] high 
- [ ] medium
- [ ] low

### How to test:
1. `firebase emulators:start`
2.  `ng serve`

2021-07-03 14:51 UTC, viv9k approved these changes
Ship it

2021-07-04 10:07 UTC, RohitVarma001 commented
I have made changes Patch 3 API Please check then Merge

2021-07-04 15:46 UTC, viv9k requested changes
Some major changes requested, the idea is really good and this is now going to get into R&D code. Good job. But please complete the required changes.

2021-07-04 15:46 UTC, viv9k commented on functions/patch3API.js
> +        desiredField = {};
remain this variable as data, as data is the most appropriate word.

2021-07-04 15:46 UTC, viv9k commented on functions/patch3API.js
> +        const newFieldValue = request.body.data.NewFieldValue;
The field name for new and old field is same i believe, so we don't need two different field names.
Let have only one field name, with old value and new value.

2021-07-04 15:46 UTC, viv9k commented on functions/patch3API.js
> +        desiredField[newField]=newFieldValue;
This is normally a key value, json works in that way. So please check if we can improve this representation.

2021-07-07 14:13 UTC, viv9k approved these changes
Ship it

2021-07-07 15:02 UTC, merged