feat(Created-Patch 2):Created API for patch2 and created frontend components for the same
Worktrolly/worktrolly pull request #205
Opened 2021-07-03 17:59 UTC by Kanishk6677

Signed-off-by: Kanishk6677 <kanishkraj6677@gmail.com>

### Functionality:
Patch 2

### Solution:
Get the field name and field value from the user to get task details based on it and update the fields with new values in all other tasks too.

### Risk level:
- [ ] high 
- [ ] medium
- [ ] low

### How to test:
1. firebase emulators : start
2. ng serve

2021-07-07 14:23 UTC, RohitVarma001 reviewed
Ship it

2021-07-07 15:04 UTC, k0malSharma commented
Resolve Conflict ASAP

2021-07-07 15:27 UTC, viv9k requested changes
Please complete the required changes

2021-07-07 15:27 UTC, viv9k commented on functions/patch2API.js
> +        });
I think this an extra closing, please fix it.

2021-07-07 15:27 UTC, viv9k commented on functions/patch2API.js
> +                desiredField[newfield]=newFieldValue;
renaming desiredField as data could sound much better.

2021-07-17 08:43 UTC, viv9k approved these changes
Ship it

2021-07-18 07:27 UTC, merged