feat(Dev/profile): Improved profile page
Worktrolly/worktrolly pull request #207
Opened 2021-07-08 14:14 UTC by sid-bagwe

### Functionality:
Improved profile page

### Solution:
Added two more fields to the Users collection (github and LinkedIn profiles)
Also displayed team name, organization name, manager email and role on the profile page
 

### Risk level:
- [ ] high 
- [x] medium
- [ ] low

### How to test:
ng serve
firebase emulators: start

2021-07-10 10:38 UTC, arjund-06 approved these changes
Ship it

2021-07-10 14:10 UTC, viv9k requested changes
Please do the required changes.

2021-07-10 14:10 UTC, viv9k commented on functions/createNewUserAPI.js
> +                    phoneNumber: "",
Better if we can check if there is a number inside PhoneNumber, is PhoneNumber is null then we must make it empty else we must update it with PhoneNumber

2021-07-10 14:10 UTC, viv9k commented on src/app/body/profile/profile.component.html
> +                        </svg>
These svg icons could be moved to a common component in icons, just check how it's done. Do this for all..

2021-07-10 14:10 UTC, viv9k commented on src/app/body/profile/profile.component.html
> +                        </svg>
These svg icons could be moved to a common component in icons, just check how it's done. Do this for all..

2021-07-10 14:10 UTC, viv9k commented on src/app/body/profile/profile.component.html
> +                        </svg>
These svg icons could be moved to a common component in icons, just check how it's done. Do this for all..

2021-07-10 14:10 UTC, viv9k commented on src/app/body/profile/profile.component.html
> +                        </svg>
These svg icons could be moved to a common component in icons, just check how it's done. Do this for all..

2021-07-10 14:10 UTC, viv9k commented on src/app/body/profile/profile.component.html
> +                        </svg>
These svg icons could be moved to a common component in icons, just check how it's done. Do this for all..

2021-07-17 08:41 UTC, viv9k approved these changes
ship it

2021-07-18 07:28 UTC, merged