Made footer
Worktrolly/worktrolly pull request #222
Opened 2021-08-11 17:45 UTC by Akshay-Jak

Signed-off-by: Akshay-Jak <akshayjani2147@gmail.com>

### Functionality:
Made the footer component added icons 

### Solution:
Made a footer component

### Risk level:
- [ ] high 
- [x] medium
- [ ] low

### How to test:
ng serve 
firebase emulators:start

![Screenshot (1129)](https://user-images.githubusercontent.com/68271366/129077720-30ad7b79-8c18-4643-bb91-1f007aeaec1b.png)

2021-08-13 04:57 UTC, arjund-06 approved these changes
Ship it

2021-08-13 11:16 UTC, viv9k commented
Ui is not looking good, for footer... Let's connect and discuss over it.

2021-08-16 13:58 UTC, viv9k requested changes
Please fix the required changes

2021-08-16 13:58 UTC, viv9k commented on src/app/app.component.css
> +}
This class is not needed now.

2021-08-20 03:26 UTC, viv9k approved these changes
Ship it

2021-08-20 13:27 UTC, merged