Feat(dev/performanceChart): Made a Team Performance chart
Worktrolly/worktrolly pull request #229
Opened 2021-08-18 13:24 UTC by sid-bagwe

Signed-off-by: sid-bagwe <siddhesh.ab@somaiya.edu>

### Functionality:
Created a team performance chart to show team's performance also the members performance

### Solution:
Used google column chart 
Fetched the required data and passed it to the chart

### Risk level:
- [ ] high 
- [x] medium
- [ ] low

### How to test:
ng serve
firebase emulators:start

2021-08-19 15:19 UTC, arjund-06 requested changes

2021-08-19 15:19 UTC, arjund-06 commented on src/app/body/board/performance-column-chart/performance-column-chart.component.ts
> +import { AuthService } from 'src/app/services/auth.service';
There is no use of ApplicationSettingsService and AuthService. Please remove these imports

2021-08-20 18:20 UTC, arjund-06 approved these changes
ship it

2021-08-21 12:51 UTC, viv9k approved these changes
Ship it

2021-08-21 13:25 UTC, merged