Activity card
Worktrolly/worktrolly pull request #230
Opened 2021-08-19 18:28 UTC by Akshay-Jak

### Functionality:
Added user email and user photo to activity card

### Solution:
added email address and photo URL to each

### Risk level:
- [ ] high 
- [x] medium
- [ ] low

### How to test:
ng serve
firebase emulators:start

![Screenshot (1185)](https://user-images.githubusercontent.com/68271366/130124097-75e21133-b562-4e94-955f-1f57c9bc514f.png)
 activity

2021-08-20 14:15 UTC, viv9k commented
The design of the card is not good please connect with me

2021-08-21 12:31 UTC, viv9k requested changes
It's not clear, please update only the changed lines. These files are having full line of changes..

2021-08-23 12:34 UTC, viv9k requested changes
unable to review it as the changes are show full file change, fix it and then raise it again.

2021-08-23 13:15 UTC, k0malSharma commented
Please resolve the merge conflicts ASAP

2021-08-28 15:22 UTC, viv9k requested changes
Remove unused logging statements

2021-08-28 15:22 UTC, viv9k commented on src/app/body/task-details/task-details.component.ts
> +    console.log(2);
Remove this logging statement

2021-08-28 15:22 UTC, viv9k commented on src/app/body/task-details/task-details.component.ts
> +        console.log(2);
Remove this logging statement

2021-08-28 15:22 UTC, viv9k commented on src/app/body/task-details/task-details.component.ts
> +    console.log(this.activityData);
Remove this logging statement

2021-08-28 15:40 UTC, viv9k approved these changes
Ship it

2021-08-28 15:50 UTC, viv9k approved these changes
Ship it.

2021-08-28 16:07 UTC, merged