Added PageNotFound component
Worktrolly/worktrolly pull request #246
Opened 2021-08-30 11:18 UTC by shibangi23

### Functionality:
Added PageNotFound component

### Solution:
Created multiple files which implement page not found component

### Risk level:
- [ ] high 
- [ ] medium
- [x] low

### How to test:
Please go to the route `localhost:4200/any` to check the component

2021-08-30 17:42 UTC, shibangi23 commented
Made some changes in the UI for 404 error display . Please review it.

2021-08-31 05:50 UTC, viv9k requested changes
Please fix it

2021-08-31 05:50 UTC, viv9k commented on src/app/pagenotfound/pagenotfound.component.html
> +		<a href="" class="link_404">Go to Home</a>
Is this working

2021-08-31 06:31 UTC, shibangi23 commented on src/app/pagenotfound/pagenotfound.component.html
> +		<a href="" class="link_404">Go to Home</a>
Yes it's working.

2021-09-02 13:09 UTC, viv9k reviewed
Need demo on this.

2021-09-03 13:52 UTC, viv9k approved these changes
Ship it

2021-09-03 14:01 UTC, merged