feat(dev/SprintGraph) : made sprint progress graph
Worktrolly/worktrolly pull request #255
Opened 2021-09-05 07:17 UTC by Pendyala-thanvi

### Functionality:
Sprint progress graph

### Solution:
The progress width increases with increase in time

### Risk level:
- [ ] high 
- [x] medium
- [ ] low

### How to test:
ng serve
firebase emulators:start

2021-09-05 07:19 UTC, arjund-06 approved these changes
Ship it

2021-09-05 07:28 UTC, viv9k commented
I need demo on this.

2021-09-07 13:10 UTC, viv9k requested changes
Please do the required changes

2021-09-07 13:10 UTC, viv9k commented on src/app/body/board/sprint-details/sprint-details.component.css
> +    border-radius: 5px;
Too much of static details, try reducing it as much as possible

2021-09-07 15:35 UTC, viv9k approved these changes
Ship it

2021-09-07 16:28 UTC, merged