Dev/smallchanges
Worktrolly/worktrolly pull request #32
Opened 2020-10-10 12:54 UTC by 05saitejaswi

Worked on the TotalCompletedTask ,when the status is completed then the task must come under TotalCompletedTask.

2020-10-10 16:07 UTC, shivamgoyal7 requested changes
Update your branch.
After these changes start the remaining task

2020-10-10 16:07 UTC, shivamgoyal7 commented on functions/index.js
> +
remove this extra space

2020-10-10 16:07 UTC, shivamgoyal7 commented on public/index.html
> +                <span type="button" class="col-md-4 col-1  material-icons" id="backToMainFromCreateNewTask">
change the id name.
And give some common back button id everywhere.

2020-10-10 16:07 UTC, shivamgoyal7 commented on public/index.html
> +
don't give extra space

2020-10-10 16:07 UTC, shivamgoyal7 commented on public/scripts/config.js
> +// For Firebase JS SDK v7.20.0 and later, measurementId is optional
you can remove this commented line

2020-10-10 16:07 UTC, shivamgoyal7 commented on public/scripts/frames.js
> +
Update your branch and you get the correct changes here.

2020-10-11 19:01 UTC, 05saitejaswi commented on functions/index.js
> +
k

2020-10-11 19:02 UTC, 05saitejaswi commented on public/scripts/config.js
> +// For Firebase JS SDK v7.20.0 and later, measurementId is optional
k

2020-10-11 19:03 UTC, 05saitejaswi commented on public/index.html
> +
k

2020-10-14 16:47 UTC, shivamgoyal7 reviewed
check

2020-10-14 16:47 UTC, shivamgoyal7 commented on public/scripts/worktrollyUI.js
> +    // var inputs = document.querySelectorAll('input');
remove commented line

2020-10-14 16:47 UTC, shivamgoyal7 commented on public/scripts/frames.js
> +    selectedDocument = "S" + selectedSprint;
remove this line no. 11

2020-10-15 06:09 UTC, 05saitejaswi commented on public/scripts/worktrollyUI.js
> +    // var inputs = document.querySelectorAll('input');
k

2020-10-15 06:10 UTC, 05saitejaswi commented on public/scripts/frames.js
> +    selectedDocument = "S" + selectedSprint;
k

2020-10-15 16:38 UTC, shivamgoyal7 approved these changes
able to merge

2020-10-15 16:48 UTC, viv9k approved these changes
Ship it

2020-10-15 16:48 UTC, viv9k commented on functions/index.js
> +
Please remove empty line

2020-10-15 16:48 UTC, merged

2020-10-16 16:31 UTC, shivamgoyal7 reviewed
hey, saitejaswi one small error is there in your code, do it asap.

2020-10-16 16:34 UTC, shivamgoyal7 reviewed
do it asap