Dev/delete
Worktrolly/worktrolly pull request #46
Opened 2020-10-27 16:08 UTC by shivamgoyal7

### Functionality:
Added delete functionality

### Solution:
Added delete task functionality and updated counter functionality accordingly.

### Risk level:
- [ ] high 

### How to test:
Added delete icon in the task description page.
Added UI functionality in worktrollyUI.js
Added backend part in index.js

2020-10-28 14:18 UTC, viv9k commented
Change the target branch to dev/sprintPage

2020-10-29 14:10 UTC, viv9k requested changes
ship it

2020-10-30 16:13 UTC, shivamgoyal7 commented
I m not getting how to do ship it??

2020-11-01 03:41 UTC, viv9k approved these changes

2020-11-01 03:41 UTC, merged