Made changes to the worktrolly ui
Worktrolly/worktrolly pull request #68
Opened 2020-12-10 18:05 UTC by arjund-06

### Functionality:
<-- please enter the functionality introduction -->

### Solution:
<-- please enter brief solution -->

### Risk level:
- [ ] high 
- [ ] medium
- [x] low

### How to test:
<-- please tell us how to test functionality/bug -->

Here are sample images of how it is looking...
### The Dashboard -
![image](https://user-images.githubusercontent.com/58979519/101811013-85480480-3b3f-11eb-894d-eeba77de5764.png)

### The Create New Task Page -
![image](https://user-images.githubusercontent.com/58979519/101811080-9db81f00-3b3f-11eb-9424-ac5906628cb8.png)

### The Create New Sprint Page - 
![image](https://user-images.githubusercontent.com/58979519/101811266-e2dc5100-3b3f-11eb-9af9-f6aeaea5415a.png)

### The Tasks - 
![image](https://user-images.githubusercontent.com/58979519/101811317-f5568a80-3b3f-11eb-88bf-c8ebd0b0142c.png)

### The Task Information -
![image](https://user-images.githubusercontent.com/58979519/101811407-1028ff00-3b40-11eb-8480-8cb81a83035d.png)

### The Log Work Page - 
![image](https://user-images.githubusercontent.com/58979519/101811542-35b60880-3b40-11eb-8b28-ac931348bc0e.png)

### The Edit Task Page - 
![image](https://user-images.githubusercontent.com/58979519/101811607-4c5c5f80-3b40-11eb-88ec-87b6131c5007.png)

2020-12-12 10:40 UTC, bighnesh0404 approved these changes

2020-12-12 10:41 UTC, bighnesh0404 approved these changes
changes are working properly without any errors and Code is ready to merge

2020-12-12 16:15 UTC, viv9k requested changes
Please do the required changes

2020-12-12 16:15 UTC, viv9k commented on worktrolly-ui/src/environments/environment.ts
> +    measurementId: "G-FEQ8PFLLCV"
revert the changes here

2020-12-12 16:15 UTC, viv9k commented on worktrolly-ui/src/app/body/create-new-session/create-new-session.component.css
> +.createNewTask{
Make it ID based changes rather than class based. Do it everywhere.

2020-12-15 13:49 UTC, viv9k commented
please fill details in worktrolly

2020-12-16 15:31 UTC, viv9k approved these changes
ship it

2020-12-16 15:32 UTC, merged