feat(backButton): added back button
Worktrolly/worktrolly pull request #71
Opened 2020-12-11 16:54 UTC by k0malSharma

Functionality:
Back button to avoid reverting to main page every time

Solution:
Added a back button on every page

Risk level:
High

How to test:
Manual test functionality by clicking on "back"

2020-12-12 17:26 UTC, shivamgoyal7 requested changes

2020-12-12 17:26 UTC, shivamgoyal7 commented on worktrolly-ui/src/app/body/task-details/edit-page/edit-page.component.ts
> +
don't use the reload method here.

2020-12-14 16:05 UTC, shivamgoyal7 approved these changes
Ready to merge

2020-12-16 15:44 UTC, viv9k requested changes
Please revert all changes in .vs folder

2020-12-16 15:44 UTC, viv9k commented on worktrolly-ui/.vs/ProjectSettings.json
> +}
Please revert these changes

2020-12-16 15:44 UTC, viv9k commented on worktrolly-ui/.vs/VSWorkspaceState.json
> +}
Please revert these changes

2020-12-16 15:51 UTC, viv9k commented on worktrolly-ui/.vs/VSWorkspaceState.json
> +}
also resolve merge conflict

2020-12-18 10:02 UTC, shivamgoyal7 commented
solve the conflict

2020-12-23 07:01 UTC, shivamgoyal7 commented
attach screenshot

2020-12-23 09:19 UTC, shivamgoyal7 approved these changes
Ship it

2020-12-23 16:12 UTC, viv9k requested changes
please do the required changes asap

2020-12-23 16:12 UTC, viv9k commented on worktrolly-ui/src/app/body/task-details/edit-page/edit-page.component.ts
> +  constructor(private functions: AngularFireFunctions, private router: Router) { }
router is not needed here

2020-12-23 16:30 UTC, viv9k commented
Please resolve merge conflict also

2020-12-23 16:44 UTC, viv9k approved these changes
Ship it

2020-12-23 16:45 UTC, merged