Dev/navbar
Worktrolly/worktrolly pull request #73
Opened 2020-12-14 04:38 UTC by Joelzac537

### Functionality:
Breadcrumbs Indicate the current page’s location within a navigational hierarchy that automatically adds separators via CSS.

### Solution:
Need to add routes

### Risk level:
- [ x] high 
- [ ] medium
- [ ] low

### How to test:
From dashboard , you can go to the create new session page and without reloading you can come back or go to any other page using breadcrumbs

2020-12-15 09:17 UTC, shivamgoyal7 approved these changes
Ready to merge

2020-12-15 09:19 UTC, shivamgoyal7 requested changes

2020-12-15 09:19 UTC, shivamgoyal7 commented on worktrolly-ui/src/app/app.module.ts
> +import { BreadcrumbComponent } from './breadcrumb/breadcrumb.component';
Remove this line

2020-12-15 09:19 UTC, shivamgoyal7 commented on worktrolly-ui/src/app/app.module.ts
> +    BreadcrumbComponent,
remove breadcrumb component

2020-12-15 10:13 UTC, Joelzac537 commented on worktrolly-ui/src/app/app.module.ts
> +    BreadcrumbComponent,
removed

2020-12-15 10:13 UTC, Joelzac537 commented on worktrolly-ui/src/app/app.module.ts
> +import { BreadcrumbComponent } from './breadcrumb/breadcrumb.component';
remolved

2020-12-15 16:02 UTC, shivamgoyal7 approved these changes
ship it

2020-12-16 15:48 UTC, viv9k commented
Please attach screenshots as well

2020-12-16 17:21 UTC, Joelzac537 commented
Screenshot's
![WorktrollyUi - Google Chrome 16-12-2020 22_46_05](https://user-images.githubusercontent.com/66463238/102383066-22e47d80-3ff1-11eb-9b5c-5fbc52717840.png)
![WorktrollyUi - Google Chrome 16-12-2020 22_46_17](https://user-images.githubusercontent.com/66463238/102383072-2546d780-3ff1-11eb-9a48-249c8fa96da9.png)
![WorktrollyUi - Google Chrome 16-12-2020 22_46_57](https://user-images.githubusercontent.com/66463238/102383147-427ba600-3ff1-11eb-8a1e-5d5410d4eeff.png)
![WorktrollyUi - Google Chrome 16-12-2020 22_47_15](https://user-images.githubusercontent.com/66463238/102383160-44456980-3ff1-11eb-98d0-5fac89e6089f.png)
![WorktrollyUi - Google Chrome 16-12-2020 22_47_28](https://user-images.githubusercontent.com/66463238/102383166-45769680-3ff1-11eb-888d-0a264c0dec55.png)
![WorktrollyUi - Google Chrome 16-12-2020 22_47_48](https://user-images.githubusercontent.com/66463238/102383168-46a7c380-3ff1-11eb-9cda-5fc3500bc3ea.png)

2020-12-26 12:34 UTC, Joelzac537 commented
Screenshots 
![WorktrollyUi - Google Chrome 26-12-2020 18_02_09](https://user-images.githubusercontent.com/66463238/103151527-d1807f00-47a4-11eb-920f-3a25f971d508.png)
![WorktrollyUi - Google Chrome 26-12-2020 18_02_18](https://user-images.githubusercontent.com/66463238/103151530-d34a4280-47a4-11eb-918f-f0416c7f0f86.png)
![WorktrollyUi - Google Chrome 26-12-2020 18_02_28](https://user-images.githubusercontent.com/66463238/103151531-d47b6f80-47a4-11eb-9220-71bb8a6a3b18.png)
![WorktrollyUi - Google Chrome 26-12-2020 18_02_50](https://user-images.githubusercontent.com/66463238/103151532-d5140600-47a4-11eb-9db9-38459c8e762d.png)
![WorktrollyUi - Google Chrome 26-12-2020 18_03_25](https://user-images.githubusercontent.com/66463238/103151533-d6453300-47a4-11eb-8fc6-737cf3f4ef70.png)
![WorktrollyUi - Google Chrome 26-12-2020 18_03_35](https://user-images.githubusercontent.com/66463238/103151535-d7766000-47a4-11eb-9e65-f9b6b292b3ab.png)

2020-12-29 09:38 UTC, viv9k commented
We can have a single component of navbar that can handle this, that will reduce lots of code

2020-12-30 12:52 UTC, viv9k requested changes
We can have directly new component for this feature.

2021-01-11 03:27 UTC, Joelzac537 commented
Updated screenshot
![WorktrollyUi - Google Chrome 11-01-2021 08_55_45](https://user-images.githubusercontent.com/66463238/104144879-0fa7b080-53eb-11eb-8ab2-00cfc52d7848.png)
![WorktrollyUi - Google Chrome 11-01-2021 08_55_54](https://user-images.githubusercontent.com/66463238/104144883-10d8dd80-53eb-11eb-8691-f7cc34a5f944.png)
![WorktrollyUi - Google Chrome 11-01-2021 08_56_06](https://user-images.githubusercontent.com/66463238/104144884-11717400-53eb-11eb-9adc-d46275990cd2.png)
![WorktrollyUi - Google Chrome 11-01-2021 08_56_15](https://user-images.githubusercontent.com/66463238/104144885-120a0a80-53eb-11eb-878d-66c553ee042c.png)
![WorktrollyUi - Google Chrome 11-01-2021 08_56_25](https://user-images.githubusercontent.com/66463238/104144886-12a2a100-53eb-11eb-8972-e8adb9a01fff.png)
![WorktrollyUi - Google Chrome 11-01-2021 08_56_38](https://user-images.githubusercontent.com/66463238/104144887-12a2a100-53eb-11eb-9816-44ea2e44828d.png)

2021-01-16 08:38 UTC, viv9k requested changes
Also give name to each component, like componentName = "abc".

And send this component name to navbar component.

Then in navbar component have an array of component names. That can be shown to the navbar component.
The component which is at the end will only be marked green.
Also perform push and pop operation in navbar component over the list of components that are in the arraylist

2021-01-16 08:38 UTC, viv9k commented on worktrolly-ui/src/app/body/task-details/log-work/log-work.component.ts
> +  taskDetails: string= "/ Task Details"
/ can be handled in navbar component.

2021-01-16 08:38 UTC, viv9k commented on worktrolly-ui/src/app/body/task-details/log-work/log-work.component.ts
> +  taskDetails: string= "/ Task Details"
Also give name to each component, like componentName = "abc".

And send this component name to navbar component.

Then in navbar component have an array of component names. That can be shown to the navbar component.
The component which is at the end will only be marked green.
Also perform push and pop operation in navbar component over the list of components that are in the arraylist

2021-01-17 17:26 UTC, viv9k requested changes
Too many rubbish changes fix them asap

2021-01-17 17:26 UTC, viv9k commented on worktrolly-ui/package.json
> +        "angular-crumbs": "^3.0.1",
Please revert the changes in this file

2021-01-17 17:26 UTC, viv9k commented on worktrolly-ui/package.json
> +        "angular-crumbs": "^3.0.1",
And also in package-lock.json

2021-01-17 17:26 UTC, viv9k commented on worktrolly-ui/src/app/body/create-new-session/create-new-session.component.spec.ts
> +});
Revert the changes in this file

2021-01-17 17:26 UTC, viv9k commented on worktrolly-ui/src/app/body/create-new-session/create-new-session.component.html
> +<div class="container py-5">
Revert the changes in this file

2021-01-17 17:26 UTC, viv9k commented on worktrolly-ui/src/app/body/create-new-sprint/create-new-sprint.component.ts
> +
Revert the changes in this file

2021-01-17 17:26 UTC, viv9k commented on worktrolly-ui/src/app/body/task-details/edit-page/edit-page.component.ts
> +  }
Remove these changes

2021-01-17 17:26 UTC, viv9k commented on worktrolly-ui/src/app/body/task-details/log-work/log-work.component.html
> +                <h3 class="pt-5 fontHeading text-white">Log Work</h3>
Revert these changes

2021-01-17 17:26 UTC, viv9k commented on worktrolly-ui/src/app/body/task-details/log-work/log-work.component.ts
> +
Remove these changes

2021-01-17 17:26 UTC, viv9k commented on worktrolly-ui/src/app/body/task-details/log-work/log-work.component.ts
> +
Also remove router

2021-01-17 17:26 UTC, viv9k commented on worktrolly-ui/src/app/body/task-details/task-details.component.html
> +            <div class="card text-dark mb-3" id="cardDescription">
Revert the changes in this file

2021-01-17 17:26 UTC, viv9k commented on worktrolly-ui/src/app/body/tasks/tasks.component.html
> +                </nav>
revert the changes done in this file

2021-01-17 17:26 UTC, viv9k commented on worktrolly-ui/src/app/services/navbar-holder.service.ts
> +
Remove unnecessary blank spaces

2021-01-17 18:01 UTC, Joelzac537 commented on worktrolly-ui/src/app/body/create-new-sprint/create-new-sprint.component.ts
> +
reverted

2021-01-17 18:06 UTC, Joelzac537 commented on worktrolly-ui/src/app/services/navbar-holder.service.ts
> +
removed

2021-01-17 18:09 UTC, Joelzac537 commented on worktrolly-ui/src/app/body/tasks/tasks.component.html
> +                </nav>
changed

2021-01-17 18:10 UTC, Joelzac537 commented on worktrolly-ui/src/app/body/task-details/task-details.component.html
> +            <div class="card text-dark mb-3" id="cardDescription">
changed

2021-01-17 18:12 UTC, Joelzac537 commented on worktrolly-ui/src/app/body/create-new-session/create-new-session.component.spec.ts
> +});
no change needed here

2021-01-17 18:12 UTC, Joelzac537 commented on worktrolly-ui/package.json
> +        "angular-crumbs": "^3.0.1",
already removed

2021-01-17 18:14 UTC, Joelzac537 commented on worktrolly-ui/src/app/body/create-new-session/create-new-session.component.html
> +<div class="container py-5">
changed

2021-01-17 18:14 UTC, Joelzac537 commented on worktrolly-ui/src/app/body/task-details/edit-page/edit-page.component.ts
> +  }
removed

2021-01-17 18:15 UTC, Joelzac537 commented on worktrolly-ui/src/app/body/task-details/log-work/log-work.component.html
> +                <h3 class="pt-5 fontHeading text-white">Log Work</h3>
changed

2021-01-18 18:23 UTC, viv9k requested changes
Remove all the unnecessary changes

2021-01-18 18:23 UTC, viv9k commented on worktrolly-ui/package.json
> -}
Revert this file

2021-01-18 18:23 UTC, viv9k commented on worktrolly-ui/src/app/app-routing.module.ts
> -  { path: 'CreateNewSession', component: CreateNewSessionComponent },
revert this file

2021-01-18 18:23 UTC, viv9k commented on worktrolly-ui/src/app/body/create-new-session/create-new-session.component.ts
> +
revert this file

2021-01-18 18:23 UTC, viv9k commented on worktrolly-ui/src/app/body/create-new-sprint/create-new-sprint.component.html
> +    <div class="mt-5 px-5 py-5" id="startNewSprint">
revert this file

2021-01-18 18:23 UTC, viv9k commented on worktrolly-ui/src/app/body/create-new-sprint/create-new-sprint.component.ts
> +
revert this file

2021-01-18 18:23 UTC, viv9k commented on worktrolly-ui/src/app/body/task-details/edit-page/edit-page.component.html
> +        <div class="card text-dark mb-3" id="editPageTaskContainer">
revert this file

2021-01-18 18:23 UTC, viv9k commented on worktrolly-ui/src/app/body/task-details/edit-page/edit-page.component.ts
> +  constructor(private functions: AngularFireFunctions, private router: Router, private navbarHolder: NavbarHolderService) { }
remove router from this component

2021-01-18 18:23 UTC, viv9k commented on worktrolly-ui/src/app/body/task-details/log-work/log-work.component.html
> +                </div>
revert this file

2021-01-18 18:23 UTC, viv9k commented on worktrolly-ui/src/app/body/task-details/log-work/log-work.component.ts
> +  constructor(private functions: AngularFireFunctions,private router: Router,private navbarHolder: NavbarHolderService) { }
remove router from this component

2021-01-18 18:23 UTC, viv9k commented on worktrolly-ui/src/app/body/tasks/tasks.component.ts
> +  constructor(private route: ActivatedRoute, private router: Router, private db: AngularFirestore, private navbarHolder: NavbarHolderService) { }
route is not needed here

2021-01-19 06:29 UTC, Joelzac537 commented on worktrolly-ui/src/app/body/task-details/log-work/log-work.component.html
> +                </div>
code is correct now

2021-01-22 12:38 UTC, viv9k commented
Please resolve merge conflict

2021-01-23 08:58 UTC, viv9k requested changes
Yet there are many nonsense changes.

2021-01-23 08:58 UTC, viv9k commented on worktrolly-ui/src/app/body/task-details/log-work/log-work.component.html
> +                </div>
Please revert this file directly

2021-01-23 08:58 UTC, viv9k commented on worktrolly-ui/src/app/body/create-new-sprint/create-new-sprint.component.ts
> +
Please revert this file

2021-01-23 08:58 UTC, viv9k commented on worktrolly-ui/src/app/body/create-new-session/create-new-session.component.html
> +        <div class="row pt-2">
Revert this file

2021-01-23 08:58 UTC, viv9k commented on worktrolly-ui/package.json
> -}
Revert this file

2021-01-23 09:51 UTC, Joelzac537 commented on worktrolly-ui/src/app/body/create-new-sprint/create-new-sprint.component.ts
> +
reverted

2021-01-23 10:13 UTC, viv9k requested changes
Please do the required changes asap

2021-01-23 10:13 UTC, viv9k commented on worktrolly-ui/src/app/body/task-details/log-work/log-work.component.html
> +                </div>
Please revert this file

2021-01-23 10:46 UTC, viv9k requested changes
restore the requested file

2021-01-23 10:46 UTC, viv9k commented on worktrolly-ui/src/app/body/create-new-session/create-new-session.component.html
> -            <div class="col">
restore this file

2021-01-23 10:46 UTC, viv9k commented on worktrolly-ui/src/app/body/create-new-sprint/create-new-sprint.component.ts
> -
Restore this file

2021-01-23 10:46 UTC, viv9k commented on worktrolly-ui/src/app/body/task-details/log-work/log-work.component.html
> +                 </div> -->
Restore this file

2021-01-23 11:51 UTC, viv9k requested changes
complete the change

2021-01-23 11:51 UTC, viv9k commented on worktrolly-ui/src/app/body/create-new-sprint/create-new-sprint.component.ts
> -
I don't see this resolved

2021-01-23 12:47 UTC, viv9k commented
I have written the code merged it into dev-angular branch, so this pr can be closed

2021-01-23 12:47 UTC, closed without merging