feat(Loader):Added Loader in All pages
Worktrolly/worktrolly pull request #76
Opened 2020-12-18 05:59 UTC by sandeep-v1404

Signed-off-by: sandeep-v1404 <valpasanisandeep@gmail.com>

### Functionality:
Added Loader to all Pages
### Solution:
To create a Loader Component

### Risk level:
- [ ] high 
- [X] medium
- [ ] low

### How to test:
1. ng serve
2. Dashboard , Tasks ,TaskDetails Contains a Loader
3. Loader after Clicking Submit in CreateNewTask ,CreateNewSprint ,EditTask ,LogWork

2020-12-21 10:21 UTC, shivamgoyal7 requested changes
Add loader = false in every catch method, because if any error will occur we need to terminate the loader.

2020-12-21 10:21 UTC, shivamgoyal7 commented on worktrolly-ui/src/app/body/create-new-session/create-new-session.component.ts
> +    this.enableLoader = true;
After completion of the request make this as a false.

2020-12-22 06:00 UTC, shivamgoyal7 approved these changes
ship it

2020-12-23 16:23 UTC, viv9k approved these changes
ship it

2020-12-23 16:24 UTC, merged