Dev/board
Worktrolly/worktrolly pull request #93
Opened 2021-01-11 15:25 UTC by arjund-06

### Functionality:
Allows the user logged in to see all his tasks right from the first sprint.

### Solution:
Created a task board button and sent the user name and filtered tasks that had the user's name as assignee. 

### Risk level:
- [ ] high 
- [X] medium
- [ ] low

### How to test:
ng serve and then click on the Task Board button on the navbar.

![image](https://user-images.githubusercontent.com/58979519/104200809-1405b500-544f-11eb-8f64-882771cc80eb.png)

2021-01-11 17:00 UTC, viv9k commented
It would be better if we have this component as Dashboard, and move current component as board.

Also make this list box a little small.

2021-01-14 13:01 UTC, shivamgoyal7 requested changes
remove the back button from the front page and add the back button in the dashboard.
Also, hide the dashboard button when we are in the dashboard page

2021-01-15 16:06 UTC, shivamgoyal7 reviewed
remove extra space from everywhere.
Add back button in the dashboard.
my dashboard(board) page is visible when the user is logged in, when the user is logged off then only the dashboard button is visible so anyone can go on the board.

2021-01-15 16:06 UTC, shivamgoyal7 commented on worktrolly-ui/src/app/body/task-board/task-board.component.ts
> +
remove all the extra space

2021-01-15 16:06 UTC, shivamgoyal7 commented on worktrolly-ui/src/app/body/task-board/task-board.component.ts
> +
remove all the extra space

2021-01-15 16:06 UTC, shivamgoyal7 commented on worktrolly-ui/src/app/body/task-board/task-board.component.ts
> +
remove all the extra space

2021-01-16 08:46 UTC, viv9k approved these changes
Ship it

2021-01-16 10:13 UTC, merged