Completed error-component
Worktrolly/worktrolly pull request #94
Opened 2021-01-15 13:05 UTC by AvinashMahanthi

### Functionality:
Create error component

### Solution:
created the component and called the function wherever the error is returned

### Risk level:
- [x] high 
- [ ] medium
- [ ] low

### How to test:
ng serve
Click on create a new task
Submit the task without entering any details.

![Screenshot (191)](https://user-images.githubusercontent.com/54079190/104730421-08243680-5760-11eb-998a-c881c81faba5.png)

2021-01-15 14:31 UTC, shivamgoyal7 requested changes
Do these changes asap

2021-01-15 14:31 UTC, shivamgoyal7 commented on worktrolly-ui/src/app/error/error.component.css
> +h1 {
Remove css from error

2021-01-15 14:31 UTC, shivamgoyal7 commented on worktrolly-ui/src/app/error/error.component.ts
> +    this.router.navigate(['/']);
Don't navigate to dashboard

2021-01-15 14:31 UTC, shivamgoyal7 commented on worktrolly-ui/src/app/error/error.component.ts
> +    this.router.navigate(['/']);
Use enable and disable here

2021-01-15 14:31 UTC, shivamgoyal7 commented on worktrolly-ui/src/app/error/error.component.html
> +        <span aria-hidden="true">&times;</span>
For close button use material icon

2021-01-15 14:31 UTC, shivamgoyal7 commented on worktrolly-ui/src/app/body/dashboard/sprint-details/sprint-details.component.ts
>        console.error("Error", error);
Add error variable to send data

2021-01-16 08:49 UTC, viv9k reviewed
Please use bootstrap model for error. Also please discuss with the stack holder for the internal functionality of errors, Since we need to implement the error codes as well.
This is not the right way to work with errors.

2021-01-18 18:27 UTC, viv9k commented
Code design is not good and code of conduct not followed. #closed

2021-01-18 18:27 UTC, closed without merging