fix(profile): 'Profile page bug fixes'
Worktrolly/worktrolly pull request #973
Opened 2023-06-23 06:40 UTC by abhishek-mishra019

### Functionality:
to fix the ui and loading issues of profile page

### Solution:
fixed the UI and date formats, data representation for new User data, and loading issues

## WtId: Dev669

### Risk level:
- [x] high 
- [ ] medium
- [ ] low

### How to test:
<-- please tell us how to test functionality/bug -->

2023-06-23 16:58 UTC, sanjaykrishna1203 requested changes

2023-06-23 16:58 UTC, sanjaykrishna1203 commented on src/app/body/profile/profile.component.ts
> +        // this.website= 'github.com'
```suggestion
      this.website = this.authService.userAppSetting.Website;
      if (this.website.includes("https://") == false && this.website != "") {
        this.website = "https://" + this.website;
        // this.website= 'github.com'
```

2023-06-23 16:58 UTC, sanjaykrishna1203 commented on src/app/body/profile/profile.component.html
> +                    <div class="row py-2" *ngIf="website != 'https://'">
```suggestion
                    <div class="row py-2" *ngIf="website">
```

2023-06-24 12:33 UTC, abhishek-mishra019 commented on src/app/body/profile/profile.component.ts
> +        // this.website= 'github.com'
committed the changes

2023-06-24 13:44 UTC, sanjaykrishna1203 approved these changes

2023-06-28 15:57 UTC, viv9k approved these changes
Approved

2023-06-29 10:52 UTC, merged