fix taskcard ui
Worktrolly/worktrolly pull request #99
Opened 2021-01-21 14:57 UTC by shreyachowdhury4

### Functionality:
fixing task card according to the requirements respectively

### Solution:
The arrangement of the taskcards in a neat manner,colours to the icons acording to the status and tooltips for better understanding.

### Risk level:
- [ ] high 
- [ ] medium
- [ x ] low

### How to test:
<img width="918" alt="worktrolly task" src="https://user-images.githubusercontent.com/73729542/105367910-f7c00000-5c26-11eb-97e2-a38b590beeb2.PNG">

2021-01-22 05:53 UTC, bighnesh0404 requested changes
Add top padding

2021-01-22 05:53 UTC, bighnesh0404 commented on worktrolly-ui/src/app/body/tasks/task-cards/task-cards.component.html
> +                <span class="material-icons" data-toggle="tooltip" style="vertical-align: middle;" data-placement="top" title="Assignee">perm_identity</span> {{task.Assignee}}
add top padding

2021-01-22 05:53 UTC, bighnesh0404 commented on worktrolly-ui/src/app/body/tasks/task-cards/task-cards.component.html
> +                <span style="font-weight: bold;" data-toggle="tooltip" data-placement="top" title="task.id">{{task.id}}</span>
add top padding

2021-01-22 05:53 UTC, bighnesh0404 commented on worktrolly-ui/src/app/body/tasks/task-cards/task-cards.component.html
> +            <div class="col-md-1 col-1 px-2">
add the top padding

2021-01-26 10:38 UTC, bighnesh0404 requested changes
merge conflict needs to be done properly otherwise it will create problem later

2021-01-26 10:38 UTC, bighnesh0404 commented on worktrolly-ui/src/app/body/tasks/task-cards/task-cards.component.css
> +<<<<<<< HEAD
remove the merge conflict code

2021-01-26 10:38 UTC, bighnesh0404 commented on worktrolly-ui/src/app/body/tasks/task-cards/task-cards.component.css
> +=======
remove it

2021-01-26 10:38 UTC, bighnesh0404 commented on worktrolly-ui/src/app/body/tasks/task-cards/task-cards.component.css
> +>>>>>>> fe1c7bac036e9b6f1042e4a14b8dfc03e2d86c21
remove this

2021-01-26 22:31 UTC, bighnesh0404 approved these changes
Ship it

2021-01-27 11:16 UTC, viv9k requested changes
Please do the required changes

2021-01-27 11:16 UTC, viv9k commented on worktrolly-ui/src/app/icons/priority-icons/priority-icons.component.html
> +    <span class="material-icons" style="color: yellow; padding: right 16px;" data-toggle="tooltip" data-placement="top" title="Low">
Move css to .css file, use color code for color, and fix padding right. It's not a right way to use padding.

2021-01-27 11:16 UTC, viv9k commented on worktrolly-ui/src/app/icons/priority-icons/priority-icons.component.html
> +    <span class="material-icons" style="color: violet; padding: right 16px;" data-toggle="tooltip" data-placement="top" title="Medium">
Move css to .css file, use color code for color, and fix padding right. It's not a right way to use padding.

2021-01-27 11:16 UTC, viv9k commented on worktrolly-ui/src/app/icons/priority-icons/priority-icons.component.html
> +    <span class="material-icons" style="color: red; padding: right 16px;" data-toggle="tooltip" data-placement="top" title="High">
Move css to .css file, use color code for color, and fix padding right. It's not a right way to use padding.

2021-01-27 11:16 UTC, viv9k commented on worktrolly-ui/src/app/icons/status-icons/status-icons.component.html
> +    <span class="material-icons" style="color: lime; padding-right:20px;" data-toggle="tooltip" data-placement="top" title="completed">
Move css to .css file, use color code for color.

2021-01-27 11:16 UTC, viv9k commented on worktrolly-ui/src/app/icons/status-icons/status-icons.component.html
> +    <span class="material-icons" style="color: rgb(255, 0, 128); padding-right:20px;" data-toggle="tooltip" data-placement="top" title="Ready to start">
Move css to .css file, use color code for color.

2021-01-27 11:16 UTC, viv9k commented on worktrolly-ui/src/app/icons/status-icons/status-icons.component.html
> +    <span class="material-icons" style="color: gray; padding-right:20px;" data-toggle="tooltip" data-placement="top" title="Blocked">
Move css to .css file, use color code for color.

2021-01-27 11:16 UTC, viv9k commented on worktrolly-ui/src/app/icons/status-icons/status-icons.component.html
> +    <span class="material-icons" style="color: #fc6a03; padding-right:20px;" data-toggle="tooltip" data-placement="top" title="Under Progress">
Move css to .css file, use color code for color.

2021-01-27 11:16 UTC, viv9k commented on worktrolly-ui/src/app/icons/status-icons/status-icons.component.html
> +    <span class="material-icons" style="color: skyblue; padding-right:20px;" data-toggle="tooltip" data-placement="top" title="Ice Box">
Move css to .css file, use color code for color.

2021-01-27 11:16 UTC, viv9k commented on worktrolly-ui/src/app/body/tasks/task-cards/task-cards.component.css
> +    font-size:15px;
Let's not increase the font-size.

2021-01-28 14:26 UTC, shreyachowdhury4 commented on worktrolly-ui/src/app/body/tasks/task-cards/task-cards.component.css
> +    font-size:15px;
I have done,could you please review it

2021-01-28 14:49 UTC, viv9k approved these changes
ship it

2021-01-29 06:58 UTC, merged